version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target_files:/app/target_files  # Mount input PST files directory
      - ./mbox_dir:/app/mbox_dir          # Mount directory for MBOX files
      - ./output:/app/output              # Mount output directory for database and attachments
    environment:
      - TZ=UTC
    command: ["python3", "main.py", "--db-path", "/app/output/emaildb.sqlite3", "--keep-mbox", "true"]
